name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'back-end/lambda/**' 
      - 'back-end/*'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

    - name: Apply Terraform changes
      run: terraform apply -auto-approve
